name: Extract Uploaded Archives

on:
  push:
    paths:
      - '**/*.zip'
      - '**/*.tar'
      - '**/*.tar.gz'
      - '**/*.tgz'

jobs:
  extract-archives:
    runs-on: ubuntu-latest

    env:
      EXTRACT_ENABLED: true
      EXTRACT_TO_ROOT: false
      DELETE_ARCHIVE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip tar

      - name: Debug Changed Files
        run: |
          echo "Files changed in this push:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Debug Archive Files
        run: |
          echo "Listing archive files:"
          find . -type f \( -name '*.zip' -o -name '*.tar' -o -name '*.tar.gz' -o -name '*.tgz' \)

      - name: Extract Archives with Debug Logs
        if: env.EXTRACT_ENABLED == 'true'
        run: |
          find . -type f \( -name '*.zip' -o -name '*.tar' -o -name '*.tar.gz' -o -name '*.tgz' \) | while read -r archive; do
            echo "Processing $archive"
            dir=$(dirname "$archive")
            filename=$(basename "$archive")

            if [ "${EXTRACT_TO_ROOT}" == "true" ]; then
              target_dir="."
            else
              target_dir="$dir/${filename%.*}"
            fi
            mkdir -p "$target_dir"
            echo "Extracting to $target_dir"

            case "$archive" in
              *.zip)
                unzip -q "$archive" -d "$target_dir" && echo "Unzipped $archive"
                ;;
              *.tar)
                tar -xf "$archive" -C "$target_dir" && echo "Extracted $archive"
                ;;
              *.tar.gz|*.tgz)
                tar -xzf "$archive" -C "$target_dir" && echo "Extracted $archive"
                ;;
              *)
                echo "Unsupported archive format: $archive"
                exit 1
                ;;
            esac

            if [ "${DELETE_ARCHIVE}" == "true" ]; then
              echo "Deleting $archive"
              rm -f "$archive"
            fi
          done

      - name: Check Repository Contents
        run: |
          echo "Repository structure after extraction:"
          ls -R

      - name: Refresh Git Index
        run: |
          git rm -rf --cached .
          git add .

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Unzipped files from archives"
            git push
          fi