name: Extract Uploaded Archives

on:
  push:
    paths:
      - '**/*.zip'
      - '**/*.tar'
      - '**/*.tar.gz'
      - '**/*.tgz'

jobs:
  extract-archives:
    runs-on: ubuntu-latest

    env:
      EXTRACT_ENABLED: true         # 是否启用解压 (true/false)
      EXTRACT_TO_ROOT: false        # 是否解压到根目录 (true/false)
      DELETE_ARCHIVE: true          # 是否解压后删除压缩包 (true/false)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip tar

      - name: Find and Extract Archives
        if: env.EXTRACT_ENABLED == 'true'
        run: |
          # 遍历所有支持的压缩包文件
          find . -type f \( -name '*.zip' -o -name '*.tar' -o -name '*.tar.gz' -o -name '*.tgz' \) | while read -r archive; do
            echo "Processing $archive"
            dir=$(dirname "$archive")
            filename=$(basename "$archive")
            
            # 目标解压目录
            if [ "${EXTRACT_TO_ROOT}" == "true" ]; then
              target_dir="."
            else
              target_dir="$dir/${filename%.*}"
            fi
            mkdir -p "$target_dir"

            # 根据文件后缀解压
            case "$archive" in
              *.zip)
                unzip -q "$archive" -d "$target_dir"
                ;;
              *.tar)
                tar -xf "$archive" -C "$target_dir"
                ;;
              *.tar.gz|*.tgz)
                tar -xzf "$archive" -C "$target_dir"
                ;;
              *)
                echo "Unsupported archive format: $archive"
                exit 1
                ;;
            esac

            # 删除压缩包（可选）
            if [ "${DELETE_ARCHIVE}" == "true" ]; then
              echo "Deleting $archive"
              rm -f "$archive"
            fi
          done

      - name: List repository content
        run: ls -R