name: Unzip and Commit Changes

on:
  push:
    paths:
      - 'docsify-develop.zip'  # 监控任何 ZIP 文件的变化

jobs:
  unzip:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 允许 GitHub Actions 写入仓库内容

    steps:
      # 第一步：检出仓库内容
      - name: Checkout repository
        uses: actions/checkout@v2

      # 第二步：解压 ZIP 文件并直接将文件放到根目录
      - name: Unzip the files
        run: |
          for zip in $(find . -name '*.zip'); do
            echo "Unzipping $zip"
            if unzip -t "$zip"; then
              # 使用临时目录解压内容
              temp_dir=$(mktemp -d)
              unzip "$zip" -d "$temp_dir"
              
              # 将解压后的内容移动到当前目录
              shopt -s dotglob
              mv "$temp_dir"/* .
              shopt -u dotglob

              # 删除 ZIP 文件和临时目录
              rm "$zip"
              rm -rf "$temp_dir"
            else
              echo "Error: $zip is corrupted, skipping."
              exit 1
            fi
          done

      # 第三步：配置 git 用户并提交更改
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 检查是否有更改
          git add .
          git diff --cached --quiet || git commit -m "Unzipped files"
          
          # 提交更改
          git push